# -*- coding: utf-8 -*-
"""
Market Cockpit Pro - Help Texts for Indicators
指標のツールチップ（helpパラメータ）用テキスト
"""

# English help texts
HELP_EN = {
    'help_Net_Liquidity': "Market's true fuel. Calculated as (Fed Assets - TGA - RRP).",
    'help_Reserves': 'Bank reserves held at the Fed.',
    'help_TGA': 'Treasury General Account - Government bank account.',
    'help_ON_RRP': 'ON RRP - Where MMFs park excess cash at the Fed.',
    'help_VIX': 'Fear Index. Above 20 signals elevated market anxiety.',
    'help_Bank_Cash': 'Cash holdings of all US commercial banks.',
    'help_Lending_Standards': 'C&I Lending Tightening - Net % of banks tightening. + = tight, - = loose.',
    'help_SRF': 'Standing Repo Facility - Domestic repo market liquidity.',
    'help_FIMA': 'FIMA Repo Facility - Foreign central bank dollar liquidity.',
    'help_SOFR': 'Secured Overnight Financing Rate - Treasury-collateralized funding cost.',
    'help_Primary': 'Primary Credit - Emergency loans to healthy banks.',
    'help_Window': 'Total Loans - Total FRB lending to financial institutions.',
    'help_SOMA_Total': 'SOMA Total Assets - Fed holdings of Treasuries and MBS.',
    'help_SOMA_Treasury': 'SOMA Treasury Holdings - Total Treasury securities held by Fed.',
    'help_SOMA_Bills': 'SOMA Bills (T-Bills) - Fed short-term Treasury holdings.',
    'help_SomaBillsRatio': 'SOMA Bills Ratio - Share of T-Bills in Fed total assets.',
    'help_M2SL': 'M2 Money Supply - Total money circulating in the economy.',
    'help_M2REAL': 'Real M2 Money Supply - Inflation-adjusted M2 (1982-84 base).',
    'help_CI_Std_Large': 'C&I Lending Standards (Large/Medium) - Above 0 = tightening.',
    'help_CI_Std_Small': 'C&I Lending Standards (Small firms) - Leading indicator for SME funding.',
    'help_CI_Demand': 'C&I Loan Demand - Corporate capex appetite.',
    'help_CI_Loans': 'C&I Loan Balance - Total commercial/industrial loans.',
    'help_CRE_Std_Construction': 'CRE Lending (Construction) - Real estate development gateway.',
    'help_CRE_Std_Office': 'CRE Lending (Office) - Refinancing difficulty indicator.',
    'help_CRE_Std_Multifamily': 'CRE Lending (Multifamily) - Residential real estate liquidity.',
    'help_CRE_Demand': 'CRE Loan Demand - Real estate investment appetite.',
    'help_CRE_Loans': 'CRE Loan Balance (Weekly) - Fastest available CRE data.',
    'help_NFCI': 'NFCI - Chicago Fed Financial Conditions. + = tight, - = loose.',
    'help_MOVE': 'MOVE Index - Bond volatility index. Often leads VIX.',
    'help_Small_Bank_Deposits': 'Small Bank Deposits - Sharp decline = bank run warning.',
    'help_Large_Bank_Deposits': 'Large Bank Deposits - Major bank deposit trends.',
    'help_CC_Delinquency': 'Credit Card Delinquency - Leading indicator of consumer stress.',
    'help_CP_Spread': 'CP-FF Spread - Corporate short-term funding stress.',
    'help_Breakeven_10Y': '10Y Breakeven - Market inflation expectations.',
    'help_Total_Loans': 'Total FRB Loans - Credit creation indicator.',
    'help_Primary_Credit': 'Primary Credit - Emergency lending to healthy banks.',
    'help_Credit_Spread': 'High Yield Spread - Junk bond risk premium.',
    'help_US_TNX': 'US 10-Year Treasury Yield - Long-term interest rate benchmark.',
    'help_EFFR': 'Effective Federal Funds Rate - Actual overnight lending rate.',
    'help_IORB': 'Interest on Reserve Balances - Rate Fed pays on bank reserves.',
    'help_FF_Upper': 'Fed Funds Target Rate (Upper) - Policy rate upper bound.',
    'help_FF_Lower': 'Fed Funds Target Rate (Lower) - Policy rate lower bound.',
    'help_EFFR_IORB': 'EFFR-IORB Spread - Gap between actual overnight rate and reserve rate. Negative is normal.',
    'help_T10Y2Y': 'Yield Curve (10Y-2Y) - Negative = recession warning.',
    'help_NFP': 'Non-Farm Payrolls - Monthly job creation.',
    'help_ADP': 'ADP Employment - Private sector job estimate.',
    'help_AHE': 'Average Hourly Earnings - Wage inflation indicator.',
    'help_UNRATE': 'Unemployment Rate - U-3 official rate.',
    'help_JOLTS': 'JOLTS Job Openings - Labor demand indicator.',
    'help_ICSA': 'Initial Claims - Weekly new unemployment filings.',
    'help_CPI': 'Consumer Price Index - Headline inflation.',
    'help_CPICore': 'Core CPI - Inflation ex food & energy.',
    'help_PPI': 'Producer Price Index - Wholesale inflation.',
    'help_CorePCE': "Core PCE - Fed's preferred inflation measure.",
    'help_RetailSales': 'Retail Sales - Consumer spending indicator.',
    'help_RealGDP': 'Real GDP - Economic output growth.',
    'help_ConsumerSent': 'Consumer Sentiment - UMich survey.',
    'help_DXY': 'Dollar Index - USD strength vs major currencies.',
    'help_USDJPY': 'USD/JPY - Dollar-Yen exchange rate.',
    'help_EURUSD': 'EUR/USD - Euro-Dollar exchange rate.',
    'help_USDCNY': 'USD/CNY - Dollar-Yuan exchange rate.',
    'help_Gold': 'Gold - Safe haven asset price.',
    'help_Silver': 'Silver - Precious metal price.',
    'help_Oil': 'Crude Oil (WTI) - Energy price.',
    'help_Copper': 'Copper - Economic activity indicator.',
    'help_BTC': 'Bitcoin - Crypto market leader.',
    'help_ETH': 'Ethereum - DeFi ecosystem base.',
    'help_SP500': 'S&P 500 - US large-cap equity index.',
    'help_NIKKEI': 'Nikkei 225 - Japan major stock index.',
    'help_Financial_Stress': 'St. Louis Fed Financial Stress Index.',
    'help_M2_Velocity': 'M2 Velocity - Money turnover rate (GDP/M2).',
    'help_Global_Liquidity_Proxy': 'GLP - Fed + ECB assets minus drains.',
    # Stablecoin & Crypto
    'help_USDT': 'Tether (USDT) - Largest stablecoin by market cap.',
    'help_USDC': 'USD Coin (USDC) - Circle-issued regulated stablecoin.',
    'help_DAI': 'DAI - Decentralized algorithmic stablecoin.',
    'help_Total_Stablecoin': 'Total Stablecoin Supply - Crypto market liquidity proxy.',
    # Leading & Housing (2026-01-22 added)
    'help_ISM_PMI': 'ISM Manufacturing PMI - Above 50 signals expansion, below 50 signals contraction.',
    'help_Housing_Starts': 'Housing Starts - New residential construction (SAAR, thousands). Leading indicator of construction activity.',
    'help_Building_Permits': 'Building Permits - Authorized building permits (SAAR, thousands). Leading indicator of future construction.',
    'help_Leading_Index': 'Philadelphia Fed Leading Index - State-level leading indicator. Positive = expansion expected.',
    # Regional Fed Manufacturing Indices (2026-01-23 added)
    'help_Empire_State_Mfg': 'Empire State Manufacturing Index - NY Fed survey. Above 0 = expansion, below 0 = contraction.',
    'help_Philly_Fed_Mfg': 'Philadelphia Fed Manufacturing Index - Mid-Atlantic region survey. Above 0 = expansion.',
    'help_Dallas_Fed_Mfg': 'Dallas Fed Manufacturing Index - Texas region survey. Above 0 = expansion.',
    'help_Richmond_Fed_Mfg': 'Richmond Fed Manufacturing Index - Fifth District survey. Above 0 = expansion.',
    # Manufacturing Output & Orders (2026-02-01 added)
    'help_INDPRO': 'Industrial Production Index - Manufacturing/mining/utilities output (2017=100). Declining trend = economic slowdown.',
    'help_NEWORDER': 'Manufacturing New Orders - Leading indicator of future production. Decline signals upcoming output drop.',
    # === Key Name Aliases (2026-01-26) ===
    'help_FedFundsUpper': 'Fed Funds Target Rate (Upper) - Policy rate upper bound.',
    'help_FedFundsLower': 'Fed Funds Target Rate (Lower) - Policy rate lower bound.',
    'help_AvgHourlyEarnings': 'Average Hourly Earnings - Wage inflation indicator.',
    # === Fed & Global (2026-01-26) ===
    'help_Fed_Assets': 'Fed Total Assets - Total balance sheet size. QE increases, QT decreases.',
    'help_ECB_Assets': 'ECB Total Assets - European Central Bank balance sheet (Billion EUR).',
    'help_Michigan_Inflation_Exp': 'Michigan 1-Year Inflation Expectations - Consumer survey-based inflation forecast.',
    # === Regional Fed Services Indices (2026-01-26) ===
    'help_Philly_Fed_Services': 'Philly Fed Non-Manufacturing Index - Services sector survey. Above 0 = expansion.',
    'help_Dallas_Fed_Services': 'Dallas Fed Services Index - Texas services sector survey. Above 0 = expansion.',
    'help_NY_Fed_Services': 'NY Fed Business Leaders Survey - Services activity. Above 0 = expansion.',
    'help_Richmond_Fed_Services': 'Richmond Fed Services Index - Fifth District services survey. Above 0 = expansion.',
    # === Banking H.8 Data (2026-01-26) ===
    'help_Credit_Card_Loans': 'Credit Card Loans - Total credit card balances at commercial banks.',
    'help_Consumer_Loans': 'Consumer Loans - Total consumer loan balances at commercial banks.',
    'help_Bank_Securities': 'Bank Securities Holdings - Treasury and agency securities held by banks.',
    'help_Bank_Deposits': 'Total Bank Deposits - All deposits at commercial banks.',
    # === Credit ETFs (2026-01-26) ===
    'help_HYG': 'iShares iBoxx High Yield Corporate Bond ETF - Junk bond market proxy.',
    'help_LQD': 'iShares iBoxx Investment Grade Corporate Bond ETF - IG credit market proxy.',
    # === FX Pairs (2026-01-26) ===
    'help_GBPUSD': 'GBP/USD - British Pound vs US Dollar exchange rate.',
    'help_USDCHF': 'USD/CHF - US Dollar vs Swiss Franc exchange rate.',
    'help_AUDUSD': 'AUD/USD - Australian Dollar vs US Dollar exchange rate.',
    # === Valuation API (2026-01-26) ===
    'help_SP500_PE': 'S&P 500 P/E Ratio - Current price-to-earnings valuation.',
    'help_NASDAQ_PE': 'NASDAQ P/E Ratio - Tech-heavy index valuation (via QQQ ETF).',
    # === Crypto Leverage API (2026-01-26) ===
    'help_BTC_Funding_Rate': 'BTC Funding Rate - Perpetual futures funding. Positive = longs pay shorts.',
    'help_BTC_Open_Interest': 'BTC Open Interest - Total open perpetual contracts. High = leveraged market.',
    'help_BTC_Long_Short_Ratio': 'BTC Long/Short Ratio - Trader positioning. >1 = more longs.',
    'help_ETH_Funding_Rate': 'ETH Funding Rate - Ethereum perpetual futures funding rate.',
    'help_ETH_Open_Interest': 'ETH Open Interest - Total open ETH perpetual contracts.',
    # === DeFi/RWA API (2026-01-26) ===
    'help_Stablecoin_Total': 'Total Stablecoin Supply - Combined market cap of all stablecoins.',
    'help_Treasury_TVL': 'Tokenized US Treasury TVL - Real World Asset value locked in protocols.',
    'help_Gold_TVL': 'Tokenized Gold TVL - Real World Asset gold value locked in protocols.',
    # === Sentiment API (2026-01-26) ===
    'help_Crypto_Fear_Greed': 'Crypto Fear & Greed Index - 0=Extreme Fear, 100=Extreme Greed.',
    'help_CNN_Fear_Greed': 'CNN Fear & Greed Index - Traditional market sentiment. 0-100 scale.',
}

# Japanese help texts
HELP_JA = {
    'help_Net_Liquidity': '【ネットリクイディティ】\n市場に出回る「真の資金量」。(FRB総資産 - TGA - RRP) で計算。',
    'help_Reserves': '【銀行準備預金】\n民間銀行がFRBに預けているお金。',
    'help_TGA': '【TGA (財務省一般口座)】\n政府の銀行口座。増加すると市場から資金吸収。',
    'help_ON_RRP': '【ON RRP】\nMMFなどがFRBにお金を預ける場所。余剰資金の滞留を示す。',
    'help_VIX': '【VIX指数】\n恐怖指数。20以上で市場の不安が高まっている状態。',
    'help_Bank_Cash': '【銀行の現金保有】\n全米の銀行が保有する現金資産の推移。',
    'help_Lending_Standards': '【C&I融資基準】\n銀行の融資態度を示す純割合。+は引締、-は緩和。',
    'help_SRF': '【Standing Repo Facility】\n国内リポ市場の流動性支援窓口。',
    'help_FIMA': '【FIMA Repo Facility】\n海外の中央銀行向けドル流動性供給。',
    'help_SOFR': '【SOFR】\n国債を担保にした資金調達コスト。急騰は現金不足を示す。',
    'help_Primary': '【Primary Credit】\n健全な銀行向けの緊急融資。急増は危険信号。',
    'help_Window': '【Total Loans】\nFRBによる金融機関への貸出総額。',
    'help_SOMA_Total': '【SOMA総資産】\nFRBが保有する国債やMBSの総額。増加=QE、減少=QT。',
    'help_SOMA_Treasury': '【SOMA国債】\nFRBが保有する国債（Treasury Securities Held Outright）の総額。',
    'help_SOMA_Bills': '【SOMA Bills (短期国債)】\nFRBが保有する短期国債。RMPで増加中。',
    'help_SomaBillsRatio': '【SOMA Bills比率】\nFRBの総資産に占める短期国債の割合。',
    'help_M2SL': '【通貨供給量 M2】\n世の中に流通しているマネーの総量。',
    'help_M2REAL': '【実質M2】\nインフレ調整済みM2 (1982-84年基準)。',
    'help_CI_Std_Large': '【C&I融資基準（大・中堅企業）】\n0を超えると貸し渋り。40%超で強力なリセッションシグナル。',
    'help_CI_Std_Small': '【C&I融資基準（小企業）】\n中小企業の資金繰りの先行指標。雇用悪化の前兆。',
    'help_CI_Demand': '【C&I融資需要】\n企業の設備投資意欲を測定。',
    'help_CI_Loans': '【C&I融資残高】\n商工業向け融資の総額。減少は信用収縮のサイン。',
    'help_CRE_Std_Construction': '【CRE融資基準（建設・土地開発）】\n不動産開発の蛇口。閉まると数年後の供給減。',
    'help_CRE_Std_Office': '【CRE融資基準（オフィス等）】\n既存物件の借り換え難易度。厳格化は価格暴落のトリガー。',
    'help_CRE_Std_Multifamily': '【CRE融資基準（集合住宅）】\n居住用不動産市場の流動性を確認。',
    'help_CRE_Demand': '【CRE融資需要】\n不動産投資意欲。減退確認の指標。',
    'help_CRE_Loans': '【CRE融資残高（週次）】\n週次で追える最速のデータ。',
    'help_NFCI': '【NFCI】\nシカゴ連銀金融環境指数。+で引締、-で緩和。',
    'help_MOVE': '【MOVE Index】\n債券恐怖指数。VIXより先に反応することが多い。',
    'help_Small_Bank_Deposits': '【地銀預金】\n急減は取り付け騒ぎの前兆。',
    'help_Large_Bank_Deposits': '【大銀行預金】\n大手銀行の預金動向。',
    'help_CC_Delinquency': '【クレカ延滞率】\n消費者ストレスの先行指標。',
    'help_CP_Spread': '【CP-FFスプレッド】\n企業短期資金調達ストレス。',
    'help_Breakeven_10Y': '【10年期待インフレ】\n市場のインフレ期待。',
    'help_Total_Loans': '【Total Loans】\nFRBによる金融機関への貸出総額。',
    'help_Primary_Credit': '【Primary Credit】\n健全な銀行向けの緊急融資。',
    'help_Credit_Spread': '【クレジットスプレッド】\nジャンク債のリスクプレミアム。',
    'help_US_TNX': '【米10年国債利回り】\n長期金利の指標。',
    'help_EFFR': '【実効FF金利】\n実際の翌日物貸出金利。',
    'help_IORB': '【準備預金金利】\nFRBが銀行準備預金に支払う金利。',
    'help_FF_Upper': '【FF誘導目標（上限）】\n政策金利の上限。',
    'help_FF_Lower': '【FF誘導目標（下限）】\n政策金利の下限。',
    'help_EFFR_IORB': '【EFFR-IORB スプレッド】\n実効金利と準備預金金利の乖離。マイナスが正常。急上昇は資金逼迫のサイン。',
    'help_T10Y2Y': '【イールドカーブ (10Y-2Y)】\nマイナス = 景気後退警告。',
    'help_NFP': '【非農業部門雇用者数】\n月次雇用増減。',
    'help_ADP': '【ADP雇用統計】\n民間雇用の推計値。',
    'help_AHE': '【平均時給】\n賃金インフレの指標。',
    'help_UNRATE': '【失業率】\nU-3公式失業率。',
    'help_JOLTS': '【JOLTS求人数】\n労働需要の指標。',
    'help_ICSA': '【新規失業保険申請件数】\n週次の新規失業申請。',
    'help_CPI': '【消費者物価指数】\nヘッドラインインフレ。',
    'help_CPICore': '【コアCPI】\n食品・エネルギー除くインフレ。',
    'help_PPI': '【生産者物価指数】\n卸売物価。',
    'help_CorePCE': '【コアPCE】\nFRB最重要視のインフレ指標。',
    'help_RetailSales': '【小売売上高】\n個人消費の指標。',
    'help_RealGDP': '【実質GDP】\n経済成長率。',
    'help_ConsumerSent': '【消費者信頼感】\nミシガン大学調査。',
    'help_DXY': '【ドルインデックス】\n主要通貨に対するドルの強さ。',
    'help_USDJPY': '【ドル円】\nドル/円為替レート。',
    'help_EURUSD': '【ユーロドル】\nユーロ/ドル為替レート。',
    'help_USDCNY': '【ドル人民元】\nドル/人民元為替レート。',
    'help_Gold': '【金】\n安全資産の価格。',
    'help_Silver': '【銀】\n貴金属価格。',
    'help_Oil': '【原油 (WTI)】\nエネルギー価格。',
    'help_Copper': '【銅】\n景気先行指標。',
    'help_BTC': '【ビットコイン】\n暗号資産市場のリーダー。',
    'help_ETH': '【イーサリアム】\nDeFiエコシステムの基盤。',
    'help_SP500': '【S&P 500】\n米国大型株指数。',
    'help_NIKKEI': '【日経225】\n日本の主要株価指数。',
    'help_Financial_Stress': '【金融ストレス指数】\nセントルイス連銀発表。',
    'help_M2_Velocity': '【M2通貨回転率】\nお金の回転速度 (GDP/M2)。',
    'help_Global_Liquidity_Proxy': '【GLP】\nFRB + ECB資産からドレインを引いた指標。',
    # Stablecoin & Crypto
    'help_USDT': '【USDT (Tether)】\n時価総額最大のステーブルコイン。',
    'help_USDC': '【USDC (Circle)】\n規制準拠のステーブルコイン。',
    'help_DAI': '【DAI】\n分散型アルゴリズムステーブルコイン。',
    'help_Total_Stablecoin': '【ステーブルコイン総供給量】\n暗号資産市場の流動性指標。',
    # Leading & Housing (2026-01-22 added)
    'help_ISM_PMI': '【ISM製造業景気指数】\n50以上=景気拡大、50未満=景気縮小。製造業の健全性を示す最重要指標の一つ。',
    'help_Housing_Starts': '【住宅着工件数】\n新規住宅建設（年率換算・千戸）。建設活動の先行指標。',
    'help_Building_Permits': '【建築許可件数】\n許可済み建築件数（年率換算・千戸）。将来の建設活動を予測する先行指標。',
    'help_Leading_Index': '【フィラデルフィア連銀景気先行指数】\n州レベルの景気先行指標。プラス=景気拡大予想、マイナス=景気後退予想。',
    # Regional Fed Manufacturing Indices (2026-01-23 added)
    'help_Empire_State_Mfg': '【エンパイアステート製造業指数】\nNY連銀の製造業調査。0超=拡大、0未満=縮小。',
    'help_Philly_Fed_Mfg': '【フィラデルフィア連銀製造業指数】\n中部大西洋地域の製造業調査。0超=拡大。',
    'help_Dallas_Fed_Mfg': '【ダラス連銀製造業指数】\nテキサス地域の製造業調査。0超=拡大。',
    'help_Richmond_Fed_Mfg': '【リッチモンド連銀製造業指数】\n第5地区の製造業調査。0超=拡大。',
    # === 製造業生産・受注 (2026-02-01 added) ===
    'help_INDPRO': '【工業生産指数】\n製造業・鉱業・電力の実質生産量（2017=100）。減少トレンドは景気悪化のサイン。',
    'help_NEWORDER': '【製造業新規受注】\n将来の生産量の先行指標。減少は今後の生産減を示唆。',
    # === キー名エイリアス (2026-01-26) ===
    'help_FedFundsUpper': '【FF誘導目標（上限）】\n政策金利の上限。',
    'help_FedFundsLower': '【FF誘導目標（下限）】\n政策金利の下限。',
    'help_AvgHourlyEarnings': '【平均時給】\n賃金インフレの指標。',
    # === FRB & グローバル (2026-01-26) ===
    'help_Fed_Assets': '【FRB総資産】\n連銀のバランスシート規模。QEで増加、QTで減少。',
    'help_ECB_Assets': '【ECB総資産】\n欧州中央銀行のバランスシート（十億ユーロ）。',
    'help_Michigan_Inflation_Exp': '【ミシガン大1年先期待インフレ】\n消費者調査に基づくインフレ予想。',
    # === 地域連銀サービス業指数 (2026-01-26) ===
    'help_Philly_Fed_Services': '【フィラデルフィア連銀非製造業指数】\nサービス業調査。0超=拡大。',
    'help_Dallas_Fed_Services': '【ダラス連銀サービス業指数】\nテキサス地域サービス業調査。0超=拡大。',
    'help_NY_Fed_Services': '【NY連銀ビジネスリーダー調査】\nサービス業景況。0超=拡大。',
    'help_Richmond_Fed_Services': '【リッチモンド連銀サービス業指数】\n第5地区サービス業調査。0超=拡大。',
    # === 銀行H.8データ (2026-01-26) ===
    'help_Credit_Card_Loans': '【クレカ残高】\n商業銀行のクレジットカード融資残高。',
    'help_Consumer_Loans': '【消費者ローン残高】\n商業銀行の消費者向けローン残高。',
    'help_Bank_Securities': '【銀行保有有価証券】\n銀行が保有する国債・政府機関債。',
    'help_Bank_Deposits': '【銀行預金総額】\n商業銀行の全預金残高。',
    # === 社債ETF (2026-01-26) ===
    'help_HYG': '【HYG（ハイイールド債ETF）】\nジャンク債市場のプロキシ。',
    'help_LQD': '【LQD（投資適格社債ETF）】\n投資適格社債市場のプロキシ。',
    # === 為替ペア (2026-01-26) ===
    'help_GBPUSD': '【ポンドドル】\n英ポンド/米ドル為替レート。',
    'help_USDCHF': '【ドルスイスフラン】\n米ドル/スイスフラン為替レート。',
    'help_AUDUSD': '【豪ドル】\n豪ドル/米ドル為替レート。',
    # === バリュエーションAPI (2026-01-26) ===
    'help_SP500_PE': '【S&P 500 P/E比率】\n現在の株価収益率によるバリュエーション。',
    'help_NASDAQ_PE': '【NASDAQ P/E比率】\nテック重視指数のバリュエーション（QQQ ETF経由）。',
    # === 仮想通貨レバレッジAPI (2026-01-26) ===
    'help_BTC_Funding_Rate': '【BTCファンディングレート】\n無期限先物の資金調達率。プラス=ロングがショートに支払い。',
    'help_BTC_Open_Interest': '【BTCオープンインタレスト】\n未決済建玉総額。高い=レバレッジ市場。',
    'help_BTC_Long_Short_Ratio': '【BTCロング/ショート比率】\nトレーダーのポジション。>1=ロング優勢。',
    'help_ETH_Funding_Rate': '【ETHファンディングレート】\nイーサリアム無期限先物の資金調達率。',
    'help_ETH_Open_Interest': '【ETHオープンインタレスト】\nETH無期限先物の未決済建玉。',
    # === DeFi/RWA API (2026-01-26) ===
    'help_Stablecoin_Total': '【ステーブルコイン総供給量】\n全ステーブルコインの合計時価総額。',
    'help_Treasury_TVL': '【トークン化米国債TVL】\nプロトコル内のRWA（米国債）価値。',
    'help_Gold_TVL': '【トークン化金TVL】\nプロトコル内のRWA（金）価値。',
    # === センチメントAPI (2026-01-26) ===
    'help_Crypto_Fear_Greed': '【仮想通貨Fear & Greed】\n0=極度の恐怖、100=極度の貪欲。',
    'help_CNN_Fear_Greed': '【CNN Fear & Greed】\n伝統市場センチメント。0-100スケール。',
}
