# -*- coding: utf-8 -*-
"""
Market Cockpit Pro - Help Texts for Indicators
指標のツールチップ（helpパラメータ）用テキスト
"""

# English help texts
HELP_EN = {
    'help_Net_Liquidity': "Market's true fuel. Calculated as (Fed Assets - TGA - RRP).",
    'help_Reserves': 'Bank reserves held at the Fed.',
    'help_TGA': 'Treasury General Account - Government bank account.',
    'help_ON_RRP': 'ON RRP - Where MMFs park excess cash at the Fed.',
    'help_VIX': 'Fear Index. Above 20 signals elevated market anxiety.',
    'help_Bank_Cash': 'Cash holdings of all US commercial banks.',
    'help_Lending_Standards': 'C&I Lending Tightening - Net % of banks tightening. + = tight, - = loose.',
    'help_SRF': 'Standing Repo Facility - Domestic repo market liquidity.',
    'help_FIMA': 'FIMA Repo Facility - Foreign central bank dollar liquidity.',
    'help_SOFR': 'Secured Overnight Financing Rate - Treasury-collateralized funding cost.',
    'help_Primary': 'Primary Credit - Emergency loans to healthy banks.',
    'help_Window': 'Total Loans - Total FRB lending to financial institutions.',
    'help_SOMA_Total': 'SOMA Total Assets - Fed holdings of Treasuries and MBS.',
    'help_SOMA_Treasury': 'SOMA Treasury Holdings - Total Treasury securities held by Fed.',
    'help_SOMA_Bills': 'SOMA Bills (T-Bills) - Fed short-term Treasury holdings.',
    'help_SomaBillsRatio': 'SOMA Bills Ratio - Share of T-Bills in Fed total assets.',
    'help_M2SL': 'M2 Money Supply - Total money circulating in the economy.',
    'help_M2REAL': 'Real M2 Money Supply - Inflation-adjusted M2 (1982-84 base).',
    'help_CI_Std_Large': 'C&I Lending Standards (Large/Medium) - Above 0 = tightening.',
    'help_CI_Std_Small': 'C&I Lending Standards (Small firms) - Leading indicator for SME funding.',
    'help_CI_Demand': 'C&I Loan Demand - Corporate capex appetite.',
    'help_CI_Loans': 'C&I Loan Balance - Total commercial/industrial loans.',
    'help_CRE_Std_Construction': 'CRE Lending (Construction) - Real estate development gateway.',
    'help_CRE_Std_Office': 'CRE Lending (Office) - Refinancing difficulty indicator.',
    'help_CRE_Std_Multifamily': 'CRE Lending (Multifamily) - Residential real estate liquidity.',
    'help_CRE_Demand': 'CRE Loan Demand - Real estate investment appetite.',
    'help_CRE_Loans': 'CRE Loan Balance (Weekly) - Fastest available CRE data.',
    'help_NFCI': 'NFCI - Chicago Fed Financial Conditions. + = tight, - = loose.',
    'help_MOVE': 'MOVE Index - Bond volatility index. Often leads VIX.',
    'help_Small_Bank_Deposits': 'Small Bank Deposits - Sharp decline = bank run warning.',
    'help_Large_Bank_Deposits': 'Large Bank Deposits - Major bank deposit trends.',
    'help_CC_Delinquency': 'Credit Card Delinquency - Leading indicator of consumer stress.',
    'help_CP_Spread': 'CP-FF Spread - Corporate short-term funding stress.',
    'help_Breakeven_10Y': '10Y Breakeven - Market inflation expectations.',
    'help_Total_Loans': 'Total FRB Loans - Credit creation indicator.',
    'help_Primary_Credit': 'Primary Credit - Emergency lending to healthy banks.',
    'help_Credit_Spread': 'High Yield Spread - Junk bond risk premium.',
    'help_US_TNX': 'US 10-Year Treasury Yield - Long-term interest rate benchmark.',
    'help_EFFR': 'Effective Federal Funds Rate - Actual overnight lending rate.',
    'help_IORB': 'Interest on Reserve Balances - Rate Fed pays on bank reserves.',
    'help_FF_Upper': 'Fed Funds Target Rate (Upper) - Policy rate upper bound.',
    'help_FF_Lower': 'Fed Funds Target Rate (Lower) - Policy rate lower bound.',
    'help_EFFR_IORB': 'EFFR-IORB Spread - Gap between actual overnight rate and reserve rate. Negative is normal.',
    'help_T10Y2Y': 'Yield Curve (10Y-2Y) - Negative = recession warning.',
    'help_NFP': 'Non-Farm Payrolls - Monthly job creation.',
    'help_ADP': 'ADP Employment - Private sector job estimate.',
    'help_AHE': 'Average Hourly Earnings - Wage inflation indicator.',
    'help_UNRATE': 'Unemployment Rate - U-3 official rate.',
    'help_JOLTS': 'JOLTS Job Openings - Labor demand indicator.',
    'help_ICSA': 'Initial Claims - Weekly new unemployment filings.',
    'help_CPI': 'Consumer Price Index - Headline inflation.',
    'help_CPICore': 'Core CPI - Inflation ex food & energy.',
    'help_PPI': 'Producer Price Index - Wholesale inflation.',
    'help_CorePCE': "Core PCE - Fed's preferred inflation measure.",
    'help_RetailSales': 'Retail Sales - Consumer spending indicator.',
    'help_RealGDP': 'Real GDP - Economic output growth.',
    'help_ConsumerSent': 'Consumer Sentiment - UMich survey.',
    'help_DXY': 'Dollar Index - USD strength vs major currencies.',
    'help_USDJPY': 'USD/JPY - Dollar-Yen exchange rate.',
    'help_EURUSD': 'EUR/USD - Euro-Dollar exchange rate.',
    'help_USDCNY': 'USD/CNY - Dollar-Yuan exchange rate.',
    'help_Gold': 'Gold - Safe haven asset price.',
    'help_Silver': 'Silver - Precious metal price.',
    'help_Oil': 'Crude Oil (WTI) - Energy price.',
    'help_Copper': 'Copper - Economic activity indicator.',
    'help_BTC': 'Bitcoin - Crypto market leader.',
    'help_ETH': 'Ethereum - DeFi ecosystem base.',
    'help_SP500': 'S&P 500 - US large-cap equity index.',
    'help_NIKKEI': 'Nikkei 225 - Japan major stock index.',
    'help_Financial_Stress': 'St. Louis Fed Financial Stress Index.',
    'help_M2_Velocity': 'M2 Velocity - Money turnover rate (GDP/M2).',
    'help_Global_Liquidity_Proxy': 'GLP - Fed + ECB assets minus drains.',
    # Stablecoin & Crypto
    'help_USDT': 'Tether (USDT) - Largest stablecoin by market cap.',
    'help_USDC': 'USD Coin (USDC) - Circle-issued regulated stablecoin.',
    'help_DAI': 'DAI - Decentralized algorithmic stablecoin.',
    'help_Total_Stablecoin': 'Total Stablecoin Supply - Crypto market liquidity proxy.',
}

# Japanese help texts
HELP_JA = {
    'help_Net_Liquidity': '【ネットリクイディティ】\n市場に出回る「真の資金量」。(FRB総資産 - TGA - RRP) で計算。',
    'help_Reserves': '【銀行準備預金】\n民間銀行がFRBに預けているお金。',
    'help_TGA': '【TGA (財務省一般口座)】\n政府の銀行口座。増加すると市場から資金吸収。',
    'help_ON_RRP': '【ON RRP】\nMMFなどがFRBにお金を預ける場所。余剰資金の滞留を示す。',
    'help_VIX': '【VIX指数】\n恐怖指数。20以上で市場の不安が高まっている状態。',
    'help_Bank_Cash': '【銀行の現金保有】\n全米の銀行が保有する現金資産の推移。',
    'help_Lending_Standards': '【C&I融資基準】\n銀行の融資態度を示す純割合。+は引締、-は緩和。',
    'help_SRF': '【Standing Repo Facility】\n国内リポ市場の流動性支援窓口。',
    'help_FIMA': '【FIMA Repo Facility】\n海外の中央銀行向けドル流動性供給。',
    'help_SOFR': '【SOFR】\n国債を担保にした資金調達コスト。急騰は現金不足を示す。',
    'help_Primary': '【Primary Credit】\n健全な銀行向けの緊急融資。急増は危険信号。',
    'help_Window': '【Total Loans】\nFRBによる金融機関への貸出総額。',
    'help_SOMA_Total': '【SOMA総資産】\nFRBが保有する国債やMBSの総額。増加=QE、減少=QT。',
    'help_SOMA_Treasury': '【SOMA国債】\nFRBが保有する国債（Treasury Securities Held Outright）の総額。',
    'help_SOMA_Bills': '【SOMA Bills (短期国債)】\nFRBが保有する短期国債。RMPで増加中。',
    'help_SomaBillsRatio': '【SOMA Bills比率】\nFRBの総資産に占める短期国債の割合。',
    'help_M2SL': '【通貨供給量 M2】\n世の中に流通しているマネーの総量。',
    'help_M2REAL': '【実質M2】\nインフレ調整済みM2 (1982-84年基準)。',
    'help_CI_Std_Large': '【C&I融資基準（大・中堅企業）】\n0を超えると貸し渋り。40%超で強力なリセッションシグナル。',
    'help_CI_Std_Small': '【C&I融資基準（小企業）】\n中小企業の資金繰りの先行指標。雇用悪化の前兆。',
    'help_CI_Demand': '【C&I融資需要】\n企業の設備投資意欲を測定。',
    'help_CI_Loans': '【C&I融資残高】\n商工業向け融資の総額。減少は信用収縮のサイン。',
    'help_CRE_Std_Construction': '【CRE融資基準（建設・土地開発）】\n不動産開発の蛇口。閉まると数年後の供給減。',
    'help_CRE_Std_Office': '【CRE融資基準（オフィス等）】\n既存物件の借り換え難易度。厳格化は価格暴落のトリガー。',
    'help_CRE_Std_Multifamily': '【CRE融資基準（集合住宅）】\n居住用不動産市場の流動性を確認。',
    'help_CRE_Demand': '【CRE融資需要】\n不動産投資意欲。減退確認の指標。',
    'help_CRE_Loans': '【CRE融資残高（週次）】\n週次で追える最速のデータ。',
    'help_NFCI': '【NFCI】\nシカゴ連銀金融環境指数。+で引締、-で緩和。',
    'help_MOVE': '【MOVE Index】\n債券恐怖指数。VIXより先に反応することが多い。',
    'help_Small_Bank_Deposits': '【地銀預金】\n急減は取り付け騒ぎの前兆。',
    'help_Large_Bank_Deposits': '【大銀行預金】\n大手銀行の預金動向。',
    'help_CC_Delinquency': '【クレカ延滞率】\n消費者ストレスの先行指標。',
    'help_CP_Spread': '【CP-FFスプレッド】\n企業短期資金調達ストレス。',
    'help_Breakeven_10Y': '【10年期待インフレ】\n市場のインフレ期待。',
    'help_Total_Loans': '【Total Loans】\nFRBによる金融機関への貸出総額。',
    'help_Primary_Credit': '【Primary Credit】\n健全な銀行向けの緊急融資。',
    'help_Credit_Spread': '【クレジットスプレッド】\nジャンク債のリスクプレミアム。',
    'help_US_TNX': '【米10年国債利回り】\n長期金利の指標。',
    'help_EFFR': '【実効FF金利】\n実際の翌日物貸出金利。',
    'help_IORB': '【準備預金金利】\nFRBが銀行準備預金に支払う金利。',
    'help_FF_Upper': '【FF誘導目標（上限）】\n政策金利の上限。',
    'help_FF_Lower': '【FF誘導目標（下限）】\n政策金利の下限。',
    'help_EFFR_IORB': '【EFFR-IORB スプレッド】\n実効金利と準備預金金利の乖離。マイナスが正常。急上昇は資金逼迫のサイン。',
    'help_T10Y2Y': '【イールドカーブ (10Y-2Y)】\nマイナス = 景気後退警告。',
    'help_NFP': '【非農業部門雇用者数】\n月次雇用増減。',
    'help_ADP': '【ADP雇用統計】\n民間雇用の推計値。',
    'help_AHE': '【平均時給】\n賃金インフレの指標。',
    'help_UNRATE': '【失業率】\nU-3公式失業率。',
    'help_JOLTS': '【JOLTS求人数】\n労働需要の指標。',
    'help_ICSA': '【新規失業保険申請件数】\n週次の新規失業申請。',
    'help_CPI': '【消費者物価指数】\nヘッドラインインフレ。',
    'help_CPICore': '【コアCPI】\n食品・エネルギー除くインフレ。',
    'help_PPI': '【生産者物価指数】\n卸売物価。',
    'help_CorePCE': '【コアPCE】\nFRB最重要視のインフレ指標。',
    'help_RetailSales': '【小売売上高】\n個人消費の指標。',
    'help_RealGDP': '【実質GDP】\n経済成長率。',
    'help_ConsumerSent': '【消費者信頼感】\nミシガン大学調査。',
    'help_DXY': '【ドルインデックス】\n主要通貨に対するドルの強さ。',
    'help_USDJPY': '【ドル円】\nドル/円為替レート。',
    'help_EURUSD': '【ユーロドル】\nユーロ/ドル為替レート。',
    'help_USDCNY': '【ドル人民元】\nドル/人民元為替レート。',
    'help_Gold': '【金】\n安全資産の価格。',
    'help_Silver': '【銀】\n貴金属価格。',
    'help_Oil': '【原油 (WTI)】\nエネルギー価格。',
    'help_Copper': '【銅】\n景気先行指標。',
    'help_BTC': '【ビットコイン】\n暗号資産市場のリーダー。',
    'help_ETH': '【イーサリアム】\nDeFiエコシステムの基盤。',
    'help_SP500': '【S&P 500】\n米国大型株指数。',
    'help_NIKKEI': '【日経225】\n日本の主要株価指数。',
    'help_Financial_Stress': '【金融ストレス指数】\nセントルイス連銀発表。',
    'help_M2_Velocity': '【M2通貨回転率】\nお金の回転速度 (GDP/M2)。',
    'help_Global_Liquidity_Proxy': '【GLP】\nFRB + ECB資産からドレインを引いた指標。',
    # Stablecoin & Crypto
    'help_USDT': '【USDT (Tether)】\n時価総額最大のステーブルコイン。',
    'help_USDC': '【USDC (Circle)】\n規制準拠のステーブルコイン。',
    'help_DAI': '【DAI】\n分散型アルゴリズムステーブルコイン。',
    'help_Total_Stablecoin': '【ステーブルコイン総供給量】\n暗号資産市場の流動性指標。',
}
